<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <ProjectReference Include="..\..\src\FiberNet.Core\FiberNet.Core.csproj" />
    <ProjectReference Include="..\..\src\FiberNet.IO\FiberNet.IO.csproj" />
  </ItemGroup>
</Project>
