<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>FiberNet Linux SAEA I/O provider with zero-copy zero-alloc completions.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" Condition="'$(TargetFramework)' == 'net8.0'" />
    <ProjectReference Include="..\FiberNet.IO\FiberNet.IO.csproj" />
  </ItemGroup>
</Project>
